### ISSUE TITLE
Replace backbone

### ISSUE THREAD

**Issue by Lxy811** [KaihuaTang/Scene-Graph-Benchmark.pytorch#208]
## ❓ Questions and Help
Hello, I see some papers will be modified for backbone experiments, I want to ask I want to change to vgg16, how can the code achieve it, change the configuration file also need to change what

**Comment by Tongling-P** [comment]
Hello, have you solved the problem? How to configure the relevant files？Thank you so much for your assistance!

**Comment by Lxy811** [comment]
> Hello, have you solved the problem? How to configure the relevant files？Thank you so much for your assistance!

I remember having the configuration file corresponding to the xml file at the end of the vgg, and finding the corresponding training code to retrain the pre-trained model

**Comment by Tongling-P** [comment]
Thank you for your reply. In addition to the red part, are there any other places that need to be modified?
![Uploading WechatIMG424.jpg…]()

**Comment by Lxy811** [comment]
I don't remember it being complicated. It's the right thing to do

**Comment by Tongling-P** [comment]
Thank you for your reply. In addition to the "CONV_BODY: "R-101-FPN" # VGG-16" part, are there any other locations that need to be modified?INPUT:
 ```
 MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN" # VGG-16
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RELATION_ON: True
  ATTRIBUTE_ON: False
  FLIP_AUG: False            # if there is any left-right relation, FLIP AUG should be false
```
